### ISSUE TITLE
Data flow test in IOCL, Jharsuguda

### ISSUE THREAD

**Issue by BijayNanda** [BijayNanda/SBdeviceflowtest#6]
FIELD TEST ON SB DEVICE’S FLOW DATA WITH LOW, MEDIUM & HIGH MODE OF BURNER REGULATOR
***(This test report is not accurate because there is some setting issue in the SB device so the device is showing high value.)***
Test Date- 13th Sept 2022
Test done by – Bijay Nanda
Place- IOCL, Jharsuguda
Device ID - J9xB7g
[Field test on SB device data. - IOCL.docx](https://github.com/BijayNanda/SBdeviceflowtest/files/9623449/Field.test.on.SB.device.data.-.IOCL.docx)

**Comment by BijayNanda** [comment]
After the SB device replacement high flow issue solved.

**Comment by BijayNanda** [comment]
After device replacement again conducted a test about "Comparison test between SB device data at different mode"
[Comparision test between SB device data at different mode ( Med & High).docx](https://github.com/BijayNanda/SBdeviceflowtest/files/9764410/Comparision.test.between.SB.device.data.at.different.mode.Med.High.docx)

**Comment by vjkajla** [comment]
The old device J9xB7g was having the settings-  the venturi settings were for 1 inch which is why it was showing high flow, no issue with the sensor and device. Once I change the settings it is working fine. 

?output
                                                                      
:85 Content. {"Bat_V":4.12,"Solar_V":0.13,"Solar_A_average":0.00,"Static_Pa":0,"
SP_mV":15.99,"DP_mV":1.24,"Differential_Pa":12.84,"Flow_lph":2927,"Temp_degC":25
.0,"RSSI":0,"ChgState":0,"Solar_A":0.00,"Network":""}
                          
                                                      Received Request (4 bytes)

?cal
                                                                         
:85 Content. {"**Venturi_d1":0.025800,"Venturi_d2":0.016000,**"SpOffset_mV":16.486,"
SpSpan_mV":36.092,"Density_kgpm3":1.1500,"DischargeCoefficient":0.7900,"FlowThre
shold":0.0056}
                                                                 

             Received Request (5 bytes): ?conf
                               
:85 Content. {"APN":"iot-eu.aer.net","APNUser":"","APNPass":"","SendPeriodMins":
60,"GSMOff_V":3.70,"GSMOn_V":3.75,"StaticEn":true,"FlowEn":true,"HighRangeDiffSe
nsor":false,"PressureGaugeLeds":false,"ChargerEnabled":true}
